### ISSUE TITLE
Created a service, but tests weren't generated

### ISSUE THREAD

**Issue by remy** [eHealthAfrica/generator-eha#7]
I selected "service" from the options and it didn't generate the tests.

Output: 

``` bash
$ yo eha:component
? Namespace: eha.login
? Component / Module name (e.g. component-name) loginService
? Description: Login service to handle auth and auth renewal
? Keywords (comma-separated) eha
? Author's name: Remy Sharp
? Author's email: remy@remysharp.com
? Homepage: https://github.com/eHealthAfrica
? GIT Repo. URL:
? Please choose what which items you'd like scaffold for:
   create bower.json
   create package.json
   create .travis.yml
   create README.md
   create CONTRIBUTING.md
   create LICENSE
   create Gruntfile.js
   create karma.conf.js
   create src/index.js
   create .jscsrc
   create .jshintrc
   create .gitignore
   create CHANGELOG.md
```

**Comment by tthew** [comment]
Hmm I don't see the service being created, let alone the tests. So something is definitely not right (i.e I think this is a bug, rather than an oversight).

One thing that I notice (and is down to poor documentation); the namespace is meant as the 'library' namespace, so e.g. `eha` (for ehealthafrica) and  component / module name should be just that, i.e. the name of the module / component (e.g `login`) rather than the actual service, directive etc, (the directive does this naming for you) and if it's more than one word should be dash separated.  The generator is expecting dash separated values and does some processing to produce the correct service / directive whatever names (camelcaseized). 

If you use the following values you _should_ get the expected behaviour (unless there's something else going on here we still haven't caught):

namespace: `eha`
module: `login`
Item: `service` (or factory)

**Comment by remy** [comment]
Yeah, re: namespace, I think I finally figured that out around 10pm last night...!

I wonder, if this is an eha specific generator, maybe the namespace should offer the default of `eha`, so the user can just hit enter to continue? Then read the directory name for the module? Although, I had expected on the first run that it would create the directory for me, and not dump into the `cwd`.

**Comment by tthew** [comment]
So actually, the original implementation defaulted to `eha` for the namespace, but based on feedback from the team (feelings were that it was too specific) I changed it to `ng`, people then complained that we shouldn't use that namespace so in the end I just removed it altogether.
